apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lnej
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kavk-tenant/rhtap-demo-app/hacbs-test-project-lnej@sha256:9463cadf2d1ed4330fc7d816ad039906ece7d7bc279360cca401856e48d16848
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
